### PR TITLE
datadog: inject trace/span ids into MDC

### PR DESCRIPTION
**Pull request by mightyguava**

### CODE REVIEW

**Comment by wesleyk** [comment]
interesting, should we request upstream for them to give us this for free?

**Comment by wesleyk** [comment]
> interesting, should we request upstream for them to give us this for free?

err actually saw your other PR where we disable automated injection? Is this what we're doing instead?>

**Comment by mightyguava** [comment]
> err actually saw your other PR where we disable automated injection? Is this what we're doing instead?

Yeah, they hard-code `dd.span_id` and `dd.trace_id`. We don't want the `dd` prefix. I think they have it to enable directly linking for tracing to logs, but we don't use datadog logs so it doesn't matter.

Could probably ask them to turn it into an option, but it's not really worth the effort to me.

**Comment by mightyguava** [comment]
Also this is based on their impl: https://github.com/DataDog/dd-trace-java/blob/master/dd-java-agent/agent-tooling/src/main/java/datadog/trace/agent/tooling/log/LogContextScopeListener.java

**Pull request merged**
