### PR TITLE
WIP setup OOM failing test to then fix

### PR DESCRIPTION
**Pull request by adrw**
WIP attempt to address https://github.com/cashapp/misk/issues/1556

### CODE REVIEW

**Comment by chris-ryan-square** [comment]
If this PR is still relevant, then please rebase and get a green CI build.
If the PR is no longer relevant please close.

This PR will be closed at the end of January 2021 otherwise.

**Review by chris-ryan-square — APPROVED** [review]

**Comment by adrw** [comment]
I don't have bandwidth to figure out this and get it to a place where it can land but the bug is very real and has forced us to turn off large suites of event consumer tests in services because of the OOM exceptions in CI.

**Comment by chris-ryan-square** [comment]
I'll leave this here for now and see if it can be taken further for a fix.

**Comment by chris-ryan-square** [comment]
This PR has been superseded by https://github.com/cashapp/misk/pull/1760

**Pull request closed without merging**
