### PR TITLE
Remove deprecated Misk Config & Resources files now in misk-config

### PR DESCRIPTION
**Pull request by adrw**

### CODE REVIEW

**Comment by jdm-square** [comment]
This is going to cause widespread breakage in topographer upgrades, right? Can we first have a topographer robot that rewrites references to the non-deprecated versions?

**Comment by adrw** [comment]
Yes, that has already landed and I won't merge this until its confirmed that it has run successfully across many repos. In staging tests, it has run successfully.

**Review by jdm-square — APPROVED** [review]
Thank you!

**Review by frojasg — APPROVED** [review]
LGTM

**Pull request merged**
