### PR TITLE
Add module to inject metric entities bound from config values

### PR DESCRIPTION
**Pull request by shanegautreau**
Adding a module and config class which allows for defining metrics entirely in YAML config.

e.g.
```yaml
metrics:
 - name: "good_dog_petting_ms"
   type: HISTOGRAM
   help: "Length of time petting best doggos"
   labelNames:
     - "breed"
     - "name"
 - name: "good_dog_enjoyed_petting"
   type: COUNTER
   help: "Count of results from petting the goodest dogs"
   labelNames:
     - "breed"
     - "name"
     - "result"
```

Then the metric can be injected by it's name
```kt
@Inject @Named("good_dog_petting_ms") lateinit var Histogram
```

### CODE REVIEW

**Comment by ewolak-sq** [comment]
Did you forget to `git add` the actual implementation?

**Comment by shanegautreau** [comment]
> Did you forget to `git add` the actual implementation?

Yes I did!

**Review by r3mariano — COMMENTED** [review]
Looks good! Would like to see some tests

**Comment by chris-ryan-square** [comment]
@shanegautreau could you bring this up to date and add some tests as per @r3mariano comment so we can get this merged.

**Comment by shanegautreau** [comment]
@chris-ryan-square I intend to get this updated and tested but haven't been able to make time. I hope to get to this soon.

**Comment by shanegautreau** [comment]
No longer want to keep up-to-date waiting for a review.

**Pull request closed without merging**
