### PR TITLE
Log org.hibernate at ERROR

### PR DESCRIPTION
**Pull request by maniksurtani**
Re: #1149 

@swankjesse I presume this would work as a sensible default unless overridden in app-specific configs?

### CODE REVIEW

**Comment by maniksurtani** [comment]
slf4j is a log API, not a logger. You'd still need a logging engine behind it. Log4j2 is the newest, with all the benefits of Logback plus some other niceties including [minimal GC impact](http://home.apache.org/~rpopma/log4j/2.6/garbagefree.html). There's almost no point in even talking about the original log4j, which is so outdated.

Hibernate uses JBoss Logging - another log bridge - that plays nice with most major logging engines, including Log4j2.

**Comment by swankjesse** [comment]
@maniksurtani so if I’m reading this right, we should:

1. Migrate from logback to log4j2 as a backend
2. Continue to use slf4j as a frontend

**Comment by maniksurtani** [comment]
Yep.

**Comment by mightyguava** [comment]
It doesn't make a difference to me, as long as we don't install 2 logging backends at the same time (that's what I removed recently), and as long as we end up logging JSON.

**Comment by swankjesse** [comment]
https://github.com/cashapp/misk/issues/1153

**Pull request merged**
