### PR TITLE
Remove vitess_schema_dir

### PR DESCRIPTION
**Pull request by tirsen**

### CODE REVIEW

**Comment by ryanhall07** [comment]
is this going to break builds? I had to update one manually to stop using `vitess_schema_dir` and i'm sure there are more

**Comment by ryanhall07** [comment]
> vitess_schema_dir

https://git.sqcorp.co/plugins/servlet/search?q=vitess_schema_dir

**Comment by tirsen** [comment]
I'm trying to do all of them yeah. I won't merge this until they're all done.

**Comment by tirsen** [comment]
I think this has been sufficiently fixed in upstream projects now. Merging.

**Pull request merged**
