### PR TITLE
Adds KInstallOnceModule

### PR DESCRIPTION
**Pull request by cconroy**
Allows for de-duped installation of a module from multiple sites. This is useful for core/library dependencies that might need to ensure installation in varying configurations.

### CODE REVIEW

**Review by swankjesse — APPROVED** [review]
Guice de-dupes most DSL bindings now automatically, though it can’t for `@Provides` functions so this is still great to have.

**Comment by frojasg** [comment]
Is there any gotcha we should considering using this function? Is there a reason why this is not included in guice?

**Review by frojasg — APPROVED** [review]

**Comment by cconroy** [comment]
> Is there any gotcha we should considering using this function? Is there a reason why this is not included in guice?

IMHO it should be included (or it should just support de-duping wholesale). TIL from Jesse's comment that guice will de-dupe some bindings, but historically it wouldn't de-dupe at all. In theory the canonical advice is "restructure your app to only bind each thing exactly once", but for library code especially that can become really unwieldy and cumbersome.

We've used this pattern widely for many years in an internal application framework without issue.

**Comment by keeferrourke** [comment]
I'm curious, is using this functionally different than writing your module as an `object MyModule: KAbstractModule()`?

**Comment by cconroy** [comment]
> I'm curious, is using this functionally different than writing your module as an `object MyModule: KAbstractModule()`?

@keeferrourke the difference is that a `KInstallOnceModule` can be safely installed multiple times (it will only be added once, and its `configure` method will only run once). If you install a subclass of `KAbstractModule` `N` times, it will be added `N` times, and there will be `N` calls to its configure method (one for each instance installed)

**Pull request merged**
