### PR TITLE
Enable gzip compression by default

### PR DESCRIPTION
**Pull request by keeferrourke**
Let's enable gzip compression for responses by default. This dramatically reduces page load times for misk apps using misk-web UIs.

Enabling this option for my service allowed me to serve javascript which was 2-3.5x smaller, and CSS which was about 9x smaller, which is such a huge win on slow home networks.

### CODE REVIEW

**Comment by swankjesse** [comment]
I’m not sure if this is a flaky test or something else:
```
JettyServiceMetricsTest > connectionMetrics() FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <153.0>
    to be equal to:
     <118.0>
    but was not.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at misk.web.JettyServiceMetricsTest.connectionMetrics(JettyServiceMetricsTest.kt:51)
```

**Comment by keeferrourke** [comment]
> I’m not sure if this is a flaky test or something else:
> 
> ```
> JettyServiceMetricsTest > connectionMetrics() FAILED
> ```

Not a flake. Looks like it was asserting bytes sent in a response.

I've updated the values to make the test pass, but I'm not sure why the connection metrics size would increase from 118b to 153b as a result of this change.

**Comment by keeferrourke** [comment]
GRPC tests seem to be timing out now.
```
> Task :misk-grpc-tests:test
    18:11:08.735 [Thread-6] INFO  o.e.jetty.server.AbstractConnector - Stopped ServerConnector@43547576{HTTP/1.1, (http/1.1)}{127.0.0.1:0}
    18:11:08.737 [Thread-6] INFO  o.e.jetty.server.AbstractConnector - Stopped ServerConnector@72f62d07{SSL, (ssl, alpn, h2, http/1.1)}{127.0.0.1:0}
    18:11:08.737 [Thread-6] INFO  o.e.jetty.server.AbstractConnector - Stopped UnixSocketConnector@75ca0d15{HTTP/1.1, (http/1.1)}{@test}
    18:11:08.738 [Thread-6] INFO  o.e.j.server.handler.ContextHandler - Stopped o.e.j.s.ServletContextHandler@2367f31f{/,null,UNAVAILABLE}

Too long with no output (exceeded 10m0s): context deadline exceeded
```

I get socket timeouts when I run the `MiskClientMiskServerTest::duplexStreaming` test locally

```
Apr. 20, 2020 2:27:22 P.M. okhttp3.internal.platform.Platform log
INFO: Callback failure for call to https://127.0.0.1:59603/...
java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:677)
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:686)
	at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.kt:382)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.kt:198)
	at okio.InflaterSource.refill(InflaterSource.kt:94)
	at okio.InflaterSource.read(InflaterSource.kt:54)
	at okio.GzipSource.read(GzipSource.kt:69)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.kt:198)
	at com.squareup.wire.internal.GrpcMessageSource.read(GrpcMessageSource.kt:39)
	at com.squareup.wire.internal.GrpcKt$readFromResponseBodyCallback$1$onResponse$1.invokeSuspend(grpc.kt:93)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:272)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:79)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.squareup.wire.internal.GrpcKt$readFromResponseBodyCallback$1.onResponse(grpc.kt:89)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:504)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)```

**Comment by swankjesse** [comment]
Do the tests pass for you on master?

**Comment by keeferrourke** [comment]
yep! `./gradlew :misk-grpcs-tests:test` passes locally off master

**Comment by keeferrourke** [comment]
Looks like Wire [already](https://github.com/square/wire/pull/1227) gzips its gRPC? Are we double compressing as a result of this change? 🤔

**Pull request merged**
