### PR TITLE
Upgrade Kotlin to 1.5.21

### PR DESCRIPTION
**Pull request by swankjesse**

### CODE REVIEW

**Comment by r3mariano** [comment]
Is the plan to manage the upgrades downstream? 1.5 has some breaking syntax changes.

**Comment by swankjesse** [comment]
Yep! I’m happy to work on that. I don’t expect it to be difficult, most of the backwards-incompatible changes are pretty exotic.
https://kotlinlang.org/docs/compatibility-guide-15.html

**Review by r3mariano — APPROVED** [review]

**Comment by swankjesse** [comment]
I need to first restore this:
https://github.com/cashapp/misk/pull/2130

And that’s blocked on an internal change that I’m currently working on.

**Comment by chris-ryan-square** [comment]
I think you'll need to ensure Dokka is updated for 1.5 to get the build to pass - I had a PR here: https://github.com/cashapp/misk/pull/2075 with the changes, so maybe you can scavenge from that?

**Comment by swankjesse** [comment]
@chris-ryan-square yeah! I updated the publish plugin and I’ll rebase this on that.

**Review by chris-ryan-square — APPROVED** [review]

**Pull request merged**
